
modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="bygonefortress"
version="1.0.0"
displayName="Bygone Fortress Plus"
logoFile="icon.png"
authors="izofar, cassiancc"
description='''Adds the original fortress from the Bygone Nether Mod - a port of Bygone Fortress to modern versions.'''

[[dependencies.bygonefortress]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bygonefortress]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"

file="META-INF/accesstransformer.cfg"
config="bygonefortress.mixins.json"